language: "perl"

perl:
  - "5.22"
  - "5.18"
  - "5.14"

services:

env:

sudo: false

addons:
    apt:
        packages:
        - unzip

before_install:
    - git clone -b bioperl-release-1-6-1 --depth 1 https://github.com/bioperl/bioperl-live.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth=1 https://github.com/samtools/htslib.git
    - cd htslib
    - make prefix=~/biodbhts install
    - export HTSLIB_DIR=
    - cd ..

install:

notifications:
  email:
    on_success: always
    on_failure: always
